---
title: "Regular Expressions"
format:
  html:
    code-fold: true
jupyter: python3
---

## Symbols

- `.`: any character (wildcard)
- `^`: start of a string
- `$`: end of a string
- `[]`: contains the following set
- `[^]`: does not contain the following set (negation)
- `|`: or
- `()`: capturing group
- `*`: 0 or more
- `+`: 1 or more
- `?`: takes values of 0 or 1
- `{n}`: Exactly n
- `{n,}`: At least n
- `{n,m}`: Between n and m(n being the smaller and m - larger)
- `\`: escape character
- `\d`: digit
- `\D`: Not a digit
- `\w`: word
- `\W`: Not a word
- `\s`: whitespace
- `\S`: Not a whitespace
- `\b`: Word Boundary

### Lookarounds
Finding patterns that come before/ after something

- `(?=)`: Positive lookahead
- `(?!)`: Negative lookahead
- `(?<=)`: Positive lookbehind
- `(?<!)`: Negative lookbehind


## Functions

### re

```{python}
#| eval: false
import re

string = '''
Lil Baby helped you get your lingo up (What?)
21 gave you false street cred
Thug made you feel like you a slime in your head (Ayy, what?)
Quavo said you can be from Northside (What?)
2 Chainz say you good, but he lied
'''
#d+ -> one or more digits
re.findall('\d+', string)

#substitute with X
re.sub(r'\d+', 'X', string)

re.split(r'\d+', string)

re.match(r'\d+', string)
```

#### On the use of r
test
You will often see the letter `r` before the string in regular expressions. This is to denote a raw string. This is important because it tells Python to ignore any special characters in the string. For example, if you want to match a backslash, you would need to use `\\` in a regular string. However, in a raw string, you can use `\`. 

### pandas

```{python}
import pandas as pd

example_df = pd.DataFrame(
    {'text': [string]}
)

example_df['text'].str.findall(r'\d+')

example_df['text'].str.replace(r'\d+', 'X')

example_df['text'].str.split(r'\d+')

example_df['text'].str.match(r'\d+')

example_df['text'].str.extract(r'(\d+)')

example_df['text'].str.extractall(r'(\d+)')

example_df['text'].str.contains(r'\d+')

example_df['text'].str.count(r'\d+')
```


```{python}
import pandas as pd
import pyarrow as pa
import re
```

```{python}
test_strings = [
    #two words without a space (plus lowercase followed by uppercase back to back)
    "Cant change the weatherMight not be forever",

    #Chorus and verse
    "[Chorus] Say you can't sleep, baby, I know that's that me espresso [verse 1]",
   #extra whitespaces
    " This 9 to 5 ain't  workin', why the hell do I work so hard? ",

    #part of the lyrics that should be stripped out
    "Where there's a will, then there's a way And I'm damn sure you lost it Embedded lyrics here", 
    "https://www.billboard.com/charts/hot-100/2025-01-11/"
]
```

```{python}
lyrics_df = pd.DataFrame(
    {"lyrics": test_strings}, dtype=pd.ArrowDtype(pa.string()) 
)

lyrics_df['lyrics']
```

## Examples

### Removing Specific Words

```{python}
lyrics_df['lyrics'].str.replace(r'Embedded.*$', '', regex = True)[3]
#r means - to be interpreted as a raw string
#find the word embedded and find anything that comes after it till the end of the string and replace it with a space
```

### Removing Extra Space

```{python}
#better not to assign variables in the beginning- cuz we might make mistakes and will have to load in the data again
lyrics_df['lyrics'].str.replace(r'^\s|\s$', '', regex=True)[2]
```

### Removing Bracketed Text

```{python}
#this will delete this whole thing cuz it begins and ends with a bracket
#lyrics_df['lyrics'].str.replace(r'\[.*\]', '', regex=True)[1]

lyrics_df['lyrics'].str.replace(r'\[.*?\]', '', regex=True)[1]
```

### Splitting Text

```{python}
lyrics_df['lyrics'].str.replace(r'([a-z])([A-Z])','\\1 \\2', regex=True)[0]
#the groups are ordered and numbered- we can refer to them and do anything we want
```

### Extracting Text
https://www.billboard.com/charts/hot-100/2025-01-11/
```{python}
re.search(r'(?<=charts/).*(?=/[0-9]{4})', lyrics_df['lyrics'][4]).group(0)
#here, a question mark means a lookaround
```

## More Work

```{python}
all_lyrics = pd.read_feather(
    'C:/Users/laksh/Downloads/complete_lyrics_2025 (1).feather', 
    dtype_backend='pyarrow'
)
```


#regular expressions match patterns in text
#they need to be as short and efficient as possible


## test
## edit 101

